using System.Collections.Generic;
using XCom.Content.Overlays;

namespace XCom.Data
{
	public enum UfoComponentType
	{
		UfoPowerSource,
		UfoNavigation,
		UfoConstruction,
		AlienFood,
		AlienEntertainment,
		AlienSurgery,
		ExaminationRoom,
		AlienAlloys
	}

	public static class UfoComponentTypeExtensions
	{
		public static UfoComponentMetadata Metadata(this UfoComponentType ufoComponentType) => metadata[ufoComponentType];

		private static readonly UfoComponentMetadata ufoPowerSource = new UfoComponentMetadata
		{
			Name = "UFO Power Source",
			RequiredResearch = ResearchType.UfoPowerSource,
			Overlay = Overlays.UfoPowerSource,
			LabelWidth = 164,
			Description = "The power source of alien craft is an anti-matter " +
				"reactor which uses Elerium (element 115) to generate powerful " +
				"gravity waves as well as other forms of energy.  The conversion " +
				"of matter to energy is an incredible 99% efficient, therefore " +
				"tiny quantities of Elerium can produce a huge amount of power.  " +
				"This unit can be reproduced easily using alien alloys."
		};

		private static readonly UfoComponentMetadata ufoNavigation = new UfoComponentMetadata
		{
			Name = "UFO Navigation",
			RequiredResearch = ResearchType.UfoNavigation,
			Overlay = Overlays.UfoNavigation,
			LabelWidth = 147,
			Description = "Alien craft use sophisticated computers to navigate " +
				"on earth and through space.  The system is based on optical " +
				"processors arranged in network fashion. The control interface " +
				"is relatively simple - the navigator controls the direction of " +
				"gravity waves generated by the power source to move the craft " +
				"in any direction. This system can be used easily by humans, and " +
				"it can be reproduced using alien alloys and other components."
		};

		private static readonly UfoComponentMetadata ufoConstruction = new UfoComponentMetadata
		{
			Name = "UFO Construction",
			RequiredResearch = ResearchType.UfoConstruction,
			Overlay = Overlays.UfoConstruction,
			LabelWidth = 147,
			Description = "Alien craft consist of three main components - a power " +
				"source, a navigation system and a hull built from alien alloys.  " +
				"The hull is specially designed to allow gravity waves to be " +
				"directed and controlled.  In addition a small quantity of Elerium " +
				"is required to fuel the power source.  Once the principles of " +
				"construction are understood, and the functions of each component " +
				"are known, then it is possible to build these types of craft."
		};

		private static readonly UfoComponentMetadata alienFood = new UfoComponentMetadata
		{
			Name = "Alien Food",
			RequiredResearch = ResearchType.AlienFood,
			Overlay = Overlays.AlienFood,
			LabelWidth = 170,
			Description = "These chambers contain various enzymes which are used to " +
				"digest the body parts of cattle, other animals and even humans.  " +
				"The liquid is then consumed as ready digested food - probably " +
				"direct to the bloodstream. This suggests a certain dependence on " +
				"earth for food - a symbiosis between earth and alien society."
		};

		private static readonly UfoComponentMetadata alienEntertainment = new UfoComponentMetadata
		{
			Name = "Alien Entertainment",
			RequiredResearch = ResearchType.AlienEntertainment,
			Overlay = Overlays.AlienEntertainment,
			LabelWidth = 145,
			Description = "The most likely function of these spheres is recreational.  " +
				"The psionic circuitry stimulates various centres of the brain.  The " +
				"effect is similar to hallucinogenic drugs.  This is the only " +
				"evidence that aliens have any cultural or recreational pastimes."
		};

		private static readonly UfoComponentMetadata alienSurgery = new UfoComponentMetadata
		{
			Name = "Alien Surgery",
			RequiredResearch = ResearchType.AlienSurgery,
			Overlay = Overlays.AlienSurgery,
			LabelWidth = 105,
			Description = "This surgical equipment uses laser cutters to extract " +
				"certain body parts from cattle and other animals.  The widespread " +
				"cattle mutilations can be accounted for by this bizarre alien " +
				"activity.  It is likely that these parts are used for nutritional " +
				"or genetic purposes."
		};

		private static readonly UfoComponentMetadata examinationRoom = new UfoComponentMetadata
		{
			Name = "Examination Room",
			RequiredResearch = ResearchType.ExaminationRoom,
			Overlay = Overlays.ExaminationRoom,
			LabelWidth = 151,
			Description = "In the past many thousands of people have claimed to " +
				"have been abducted by aliens, sometimes repeatedly.  The truth is " +
				"far more horrific.  Humans are abducted, researched and monitored.  " +
				"The best specimens have genetic material extracted.  Women have " +
				"human-alien hybrid fetuses implanted, and then removed several " +
				"months later.  Who knows what sinister motives the aliens have?"
		};

		private static readonly UfoComponentMetadata alienAlloys = new UfoComponentMetadata
		{
			Name = "Alien Alloys",
			RequiredResearch = ResearchType.AlienAlloys,
			Overlay = Overlays.AlienAlloys,
			LabelWidth = 140,
			Description = "Alien craft are constructed from special alloys with " +
				"unique properties.  They are extremely light and durable, and can " +
				"be molded by electro-magnetic methods.  This material can be " +
				"reproduced and used in many kinds of manufacturing processes."
		};

		private static readonly Dictionary<UfoComponentType, UfoComponentMetadata> metadata = new Dictionary<UfoComponentType, UfoComponentMetadata>
		{
			{ UfoComponentType.UfoPowerSource, ufoPowerSource },
			{ UfoComponentType.UfoNavigation, ufoNavigation },
			{ UfoComponentType.UfoConstruction, ufoConstruction },
			{ UfoComponentType.AlienFood, alienFood },
			{ UfoComponentType.AlienEntertainment, alienEntertainment },
			{ UfoComponentType.AlienSurgery, alienSurgery },
			{ UfoComponentType.ExaminationRoom, examinationRoom },
			{ UfoComponentType.AlienAlloys, alienAlloys }
		};
	}
}
