using System.Collections.Generic;

namespace XCom.Music
{
	public static class TimedSoundEffects
	{
		public static Dictionary<int, IntroductionSoundEffect> Introduction =>
			new Dictionary<int, IntroductionSoundEffect>
			{
				{ 121, IntroductionSoundEffect.Whoosh },
				{ 133, IntroductionSoundEffect.Hum },
				{ 154, IntroductionSoundEffect.Roar1 },
				{ 175, IntroductionSoundEffect.Roar1 },
				{ 200, IntroductionSoundEffect.Plasma },
				{ 202, IntroductionSoundEffect.Plasma },
				{ 204, IntroductionSoundEffect.Plasma },
				{ 206, IntroductionSoundEffect.Plasma },
				{ 209, IntroductionSoundEffect.DeathScreamMale },
				{ 215, IntroductionSoundEffect.Plasma },
				{ 217, IntroductionSoundEffect.Plasma },
				{ 219, IntroductionSoundEffect.Roar2 },
				{ 225, IntroductionSoundEffect.Plasma },
				{ 227, IntroductionSoundEffect.Plasma },
				{ 229, IntroductionSoundEffect.DeathScreamFemale },
				{ 235, IntroductionSoundEffect.Plasma },
				{ 237, IntroductionSoundEffect.Plasma },
				{ 239, IntroductionSoundEffect.Roar3 },
				{ 245, IntroductionSoundEffect.Plasma },
				{ 247, IntroductionSoundEffect.Plasma },
				{ 313, IntroductionSoundEffect.Beep },
				{ 318, IntroductionSoundEffect.Beep },
				{ 324, IntroductionSoundEffect.Beep },
				{ 330, IntroductionSoundEffect.Computer },
				{ 394, IntroductionSoundEffect.Warning },
				{ 408, IntroductionSoundEffect.Warning },
				{ 415, IntroductionSoundEffect.UfoDetected },
				{ 430, IntroductionSoundEffect.Chatter },
				{ 464, IntroductionSoundEffect.TakeOff },
				{ 498, IntroductionSoundEffect.Whoosh },
				{ 511, IntroductionSoundEffect.Landing },
				{ 542, IntroductionSoundEffect.OpenHatch },
				{ 581, IntroductionSoundEffect.Shot },
				{ 583, IntroductionSoundEffect.Shot },
				{ 585, IntroductionSoundEffect.Shot },
				{ 587, IntroductionSoundEffect.Shot },
				{ 589, IntroductionSoundEffect.Shot },
				{ 591, IntroductionSoundEffect.Shot },
				{ 593, IntroductionSoundEffect.Shot },
				{ 595, IntroductionSoundEffect.Shot },
				{ 597, IntroductionSoundEffect.Shot },
				{ 599, IntroductionSoundEffect.Shot },
				{ 601, IntroductionSoundEffect.Shot },
				{ 603, IntroductionSoundEffect.Shot },
				{ 605, IntroductionSoundEffect.Shot },
				{ 626, IntroductionSoundEffect.Cannon },
				{ 634, IntroductionSoundEffect.DeadAlien1 },
				{ 638, IntroductionSoundEffect.Cannon },
				{ 650, IntroductionSoundEffect.DeadAlien2 },
				{ 654, IntroductionSoundEffect.Cannon },
				{ 666, IntroductionSoundEffect.DeadAlien3 },
				{ 670, IntroductionSoundEffect.Cannon },
				{ 705, IntroductionSoundEffect.Roar4 },
				{ 722, IntroductionSoundEffect.Shot },
				{ 724, IntroductionSoundEffect.Shot },
				{ 726, IntroductionSoundEffect.Shot },
				{ 728, IntroductionSoundEffect.Shot },
				{ 730, IntroductionSoundEffect.Cannon },
				{ 745, IntroductionSoundEffect.Teleport },
				{ 755, IntroductionSoundEffect.Teleport },
				{ 760, IntroductionSoundEffect.Teleport },
				{ 786, IntroductionSoundEffect.Whoosh }
			};
	}
}
