<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>XCom</RootNamespace>
		<AssemblyName>XCom</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<Content Remove="C:\Users\jacobb\.nuget\packages\sharpgl.winforms\3.1.1\contentFiles\any\netcoreapp3.1\SharpGL.ico" />
		<Content Remove="C:\Users\jacobb\.nuget\packages\sharpgl.winforms\3.1.1\contentFiles\any\netcoreapp3.1\SharpGL.png" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="SharpGL" Version="3.1.1" />
		<PackageReference Include="SharpGL.WinForms" Version="3.1.1" />
	</ItemGroup>
</Project>
